# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LivingspaceToolkitMain.ui',
# licensing of 'LivingspaceToolkitMain.ui' applies.
#
# Created: Tue Oct  1 14:35:07 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 922)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(818, 1000))
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(800, 16777215))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.studio_tab = QtWidgets.QWidget()
        self.studio_tab.setObjectName("studio_tab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.studio_tab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.st_scenario_gbox = QtWidgets.QGroupBox(self.studio_tab)
        self.st_scenario_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.st_scenario_gbox.setObjectName("st_scenario_gbox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.st_scenario_gbox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.st_scenario1_radio = QtWidgets.QRadioButton(self.st_scenario_gbox)
        self.st_scenario1_radio.setCheckable(True)
        self.st_scenario1_radio.setChecked(False)
        self.st_scenario1_radio.setObjectName("st_scenario1_radio")
        self.horizontalLayout_9.addWidget(self.st_scenario1_radio)
        self.st_scenario2_radio = QtWidgets.QRadioButton(self.st_scenario_gbox)
        self.st_scenario2_radio.setObjectName("st_scenario2_radio")
        self.horizontalLayout_9.addWidget(self.st_scenario2_radio)
        self.st_scenario3_radio = QtWidgets.QRadioButton(self.st_scenario_gbox)
        self.st_scenario3_radio.setObjectName("st_scenario3_radio")
        self.horizontalLayout_9.addWidget(self.st_scenario3_radio)
        self.st_scenario4_radio = QtWidgets.QRadioButton(self.st_scenario_gbox)
        self.st_scenario4_radio.setObjectName("st_scenario4_radio")
        self.horizontalLayout_9.addWidget(self.st_scenario4_radio)
        self.st_scenario5_radio = QtWidgets.QRadioButton(self.st_scenario_gbox)
        self.st_scenario5_radio.setObjectName("st_scenario5_radio")
        self.horizontalLayout_9.addWidget(self.st_scenario5_radio)
        self.verticalLayout_21.addWidget(self.st_scenario_gbox)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.st_pitch_gbox = QtWidgets.QGroupBox(self.studio_tab)
        self.st_pitch_gbox.setEnabled(True)
        self.st_pitch_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.st_pitch_gbox.setMaximumSize(QtCore.QSize(150, 80))
        self.st_pitch_gbox.setFlat(False)
        self.st_pitch_gbox.setCheckable(False)
        self.st_pitch_gbox.setObjectName("st_pitch_gbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.st_pitch_gbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.st_pitch_label = QtWidgets.QLabel(self.st_pitch_gbox)
        self.st_pitch_label.setObjectName("st_pitch_label")
        self.gridLayout_2.addWidget(self.st_pitch_label, 2, 1, 1, 1)
        self.st_angle_radio = QtWidgets.QRadioButton(self.st_pitch_gbox)
        self.st_angle_radio.setObjectName("st_angle_radio")
        self.gridLayout_2.addWidget(self.st_angle_radio, 0, 1, 1, 1)
        self.st_ratio_radio = QtWidgets.QRadioButton(self.st_pitch_gbox)
        self.st_ratio_radio.setObjectName("st_ratio_radio")
        self.gridLayout_2.addWidget(self.st_ratio_radio, 0, 0, 1, 1)
        self.st_pitch_editbox = QtWidgets.QLineEdit(self.st_pitch_gbox)
        self.st_pitch_editbox.setEnabled(True)
        self.st_pitch_editbox.setObjectName("st_pitch_editbox")
        self.gridLayout_2.addWidget(self.st_pitch_editbox, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.st_pitch_gbox)
        self.st_overhang_label = QtWidgets.QLabel(self.studio_tab)
        self.st_overhang_label.setMaximumSize(QtCore.QSize(75, 16777215))
        self.st_overhang_label.setObjectName("st_overhang_label")
        self.verticalLayout_2.addWidget(self.st_overhang_label)
        self.st_overhang_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_overhang_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_overhang_editbox.setObjectName("st_overhang_editbox")
        self.verticalLayout_2.addWidget(self.st_overhang_editbox)
        self.st_roof_gbox = QtWidgets.QGroupBox(self.studio_tab)
        self.st_roof_gbox.setMinimumSize(QtCore.QSize(0, 75))
        self.st_roof_gbox.setMaximumSize(QtCore.QSize(150, 75))
        self.st_roof_gbox.setObjectName("st_roof_gbox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.st_roof_gbox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.st_eco_radio = QtWidgets.QRadioButton(self.st_roof_gbox)
        self.st_eco_radio.setCheckable(True)
        self.st_eco_radio.setChecked(False)
        self.st_eco_radio.setObjectName("st_eco_radio")
        self.verticalLayout_9.addWidget(self.st_eco_radio)
        self.st_al_radio = QtWidgets.QRadioButton(self.st_roof_gbox)
        self.st_al_radio.setObjectName("st_al_radio")
        self.verticalLayout_9.addWidget(self.st_al_radio)
        self.verticalLayout_2.addWidget(self.st_roof_gbox)
        self.st_thickness_label = QtWidgets.QLabel(self.studio_tab)
        self.st_thickness_label.setMaximumSize(QtCore.QSize(125, 16777215))
        self.st_thickness_label.setObjectName("st_thickness_label")
        self.verticalLayout_2.addWidget(self.st_thickness_label)
        self.st_thick_combo = QtWidgets.QComboBox(self.studio_tab)
        self.st_thick_combo.setMaximumSize(QtCore.QSize(125, 16777215))
        self.st_thick_combo.setObjectName("st_thick_combo")
        self.verticalLayout_2.addWidget(self.st_thick_combo)
        self.st_panel_gbox = QtWidgets.QGroupBox(self.studio_tab)
        self.st_panel_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.st_panel_gbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.st_panel_gbox.setObjectName("st_panel_gbox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.st_panel_gbox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.st_3ply_radio = QtWidgets.QRadioButton(self.st_panel_gbox)
        self.st_3ply_radio.setCheckable(True)
        self.st_3ply_radio.setChecked(False)
        self.st_3ply_radio.setObjectName("st_3ply_radio")
        self.verticalLayout_10.addWidget(self.st_3ply_radio)
        self.st_4ply_radio = QtWidgets.QRadioButton(self.st_panel_gbox)
        self.st_4ply_radio.setObjectName("st_4ply_radio")
        self.verticalLayout_10.addWidget(self.st_4ply_radio)
        self.verticalLayout_2.addWidget(self.st_panel_gbox)
        self.st_width_label = QtWidgets.QLabel(self.studio_tab)
        self.st_width_label.setObjectName("st_width_label")
        self.verticalLayout_2.addWidget(self.st_width_label)
        self.st_width_combo = QtWidgets.QComboBox(self.studio_tab)
        self.st_width_combo.setMaximumSize(QtCore.QSize(125, 16777215))
        self.st_width_combo.setObjectName("st_width_combo")
        self.verticalLayout_2.addWidget(self.st_width_combo)
        self.st_endcut_gbox = QtWidgets.QGroupBox(self.studio_tab)
        self.st_endcut_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.st_endcut_gbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.st_endcut_gbox.setObjectName("st_endcut_gbox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.st_endcut_gbox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.st_endcut1_radio = QtWidgets.QRadioButton(self.st_endcut_gbox)
        self.st_endcut1_radio.setCheckable(True)
        self.st_endcut1_radio.setChecked(False)
        self.st_endcut1_radio.setObjectName("st_endcut1_radio")
        self.verticalLayout_11.addWidget(self.st_endcut1_radio)
        self.st_endcut2_radio = QtWidgets.QRadioButton(self.st_endcut_gbox)
        self.st_endcut2_radio.setObjectName("st_endcut2_radio")
        self.verticalLayout_11.addWidget(self.st_endcut2_radio)
        self.st_endcut3_radio = QtWidgets.QRadioButton(self.st_endcut_gbox)
        self.st_endcut3_radio.setObjectName("st_endcut3_radio")
        self.verticalLayout_11.addWidget(self.st_endcut3_radio)
        self.verticalLayout_2.addWidget(self.st_endcut_gbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.st_peakpanel_label = QtWidgets.QLabel(self.studio_tab)
        self.st_peakpanel_label.setObjectName("st_peakpanel_label")
        self.verticalLayout_12.addWidget(self.st_peakpanel_label)
        self.st_peakpanel_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_peakpanel_editbox.setMinimumSize(QtCore.QSize(75, 0))
        self.st_peakpanel_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_peakpanel_editbox.setObjectName("st_peakpanel_editbox")
        self.verticalLayout_12.addWidget(self.st_peakpanel_editbox)
        self.st_wall_label = QtWidgets.QLabel(self.studio_tab)
        self.st_wall_label.setObjectName("st_wall_label")
        self.verticalLayout_12.addWidget(self.st_wall_label)
        self.st_bwallheight_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_bwallheight_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_bwallheight_editbox.setObjectName("st_bwallheight_editbox")
        self.verticalLayout_12.addWidget(self.st_bwallheight_editbox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.st_fig1_label = QtWidgets.QLabel(self.studio_tab)
        self.st_fig1_label.setMinimumSize(QtCore.QSize(375, 250))
        self.st_fig1_label.setMaximumSize(QtCore.QSize(375, 250))
        self.st_fig1_label.setObjectName("st_fig1_label")
        self.horizontalLayout.addWidget(self.st_fig1_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem3)
        self.st_awall_label = QtWidgets.QLabel(self.studio_tab)
        self.st_awall_label.setObjectName("st_awall_label")
        self.verticalLayout_17.addWidget(self.st_awall_label)
        self.st_awall_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_awall_editbox.setMinimumSize(QtCore.QSize(75, 0))
        self.st_awall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_awall_editbox.setObjectName("st_awall_editbox")
        self.verticalLayout_17.addWidget(self.st_awall_editbox)
        self.st_bwall_label = QtWidgets.QLabel(self.studio_tab)
        self.st_bwall_label.setObjectName("st_bwall_label")
        self.verticalLayout_17.addWidget(self.st_bwall_label)
        self.st_bwall_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_bwall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_bwall_editbox.setObjectName("st_bwall_editbox")
        self.verticalLayout_17.addWidget(self.st_bwall_editbox)
        self.st_cwall_label = QtWidgets.QLabel(self.studio_tab)
        self.st_cwall_label.setObjectName("st_cwall_label")
        self.verticalLayout_17.addWidget(self.st_cwall_label)
        self.st_cwall_editbox = QtWidgets.QLineEdit(self.studio_tab)
        self.st_cwall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.st_cwall_editbox.setObjectName("st_cwall_editbox")
        self.verticalLayout_17.addWidget(self.st_cwall_editbox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.st_floor_label = QtWidgets.QLabel(self.studio_tab)
        self.st_floor_label.setMinimumSize(QtCore.QSize(375, 250))
        self.st_floor_label.setMaximumSize(QtCore.QSize(375, 250))
        self.st_floor_label.setObjectName("st_floor_label")
        self.horizontalLayout_2.addWidget(self.st_floor_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.frame = QtWidgets.QFrame(self.studio_tab)
        self.frame.setMinimumSize(QtCore.QSize(175, 125))
        self.frame.setMaximumSize(QtCore.QSize(175, 125))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.st_soffit_box = QtWidgets.QLineEdit(self.frame)
        self.st_soffit_box.setMaximumSize(QtCore.QSize(75, 25))
        self.st_soffit_box.setObjectName("st_soffit_box")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.st_soffit_box)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.st_drip_box = QtWidgets.QLineEdit(self.frame)
        self.st_drip_box.setMaximumSize(QtCore.QSize(75, 25))
        self.st_drip_box.setObjectName("st_drip_box")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.st_drip_box)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.st_roof_box = QtWidgets.QLineEdit(self.frame)
        self.st_roof_box.setMaximumSize(QtCore.QSize(75, 25))
        self.st_roof_box.setObjectName("st_roof_box")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.st_roof_box)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.st_peak_box = QtWidgets.QLineEdit(self.frame)
        self.st_peak_box.setMaximumSize(QtCore.QSize(75, 25))
        self.st_peak_box.setObjectName("st_peak_box")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.st_peak_box)
        self.verticalLayout_7.addWidget(self.frame)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_21.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.studio_tab, "")
        self.cathedral_tab = QtWidgets.QWidget()
        self.cathedral_tab.setObjectName("cathedral_tab")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.cathedral_tab)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.ca_scenario_gbox = QtWidgets.QGroupBox(self.cathedral_tab)
        self.ca_scenario_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.ca_scenario_gbox.setObjectName("ca_scenario_gbox")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.ca_scenario_gbox)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ca_scenario1_radio = QtWidgets.QRadioButton(self.ca_scenario_gbox)
        self.ca_scenario1_radio.setCheckable(True)
        self.ca_scenario1_radio.setChecked(False)
        self.ca_scenario1_radio.setObjectName("ca_scenario1_radio")
        self.horizontalLayout_10.addWidget(self.ca_scenario1_radio)
        self.ca_scenario2_radio = QtWidgets.QRadioButton(self.ca_scenario_gbox)
        self.ca_scenario2_radio.setObjectName("ca_scenario2_radio")
        self.horizontalLayout_10.addWidget(self.ca_scenario2_radio)
        self.ca_scenario3_radio = QtWidgets.QRadioButton(self.ca_scenario_gbox)
        self.ca_scenario3_radio.setObjectName("ca_scenario3_radio")
        self.horizontalLayout_10.addWidget(self.ca_scenario3_radio)
        self.ca_scenario4_radio = QtWidgets.QRadioButton(self.ca_scenario_gbox)
        self.ca_scenario4_radio.setObjectName("ca_scenario4_radio")
        self.horizontalLayout_10.addWidget(self.ca_scenario4_radio)
        self.ca_scenario5_radio = QtWidgets.QRadioButton(self.ca_scenario_gbox)
        self.ca_scenario5_radio.setObjectName("ca_scenario5_radio")
        self.horizontalLayout_10.addWidget(self.ca_scenario5_radio)
        self.verticalLayout_22.addWidget(self.ca_scenario_gbox)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ca_pitch_gbox = QtWidgets.QGroupBox(self.cathedral_tab)
        self.ca_pitch_gbox.setEnabled(True)
        self.ca_pitch_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.ca_pitch_gbox.setMaximumSize(QtCore.QSize(150, 80))
        self.ca_pitch_gbox.setCheckable(False)
        self.ca_pitch_gbox.setObjectName("ca_pitch_gbox")
        self.gridLayout = QtWidgets.QGridLayout(self.ca_pitch_gbox)
        self.gridLayout.setObjectName("gridLayout")
        self.ca_ratio_radio = QtWidgets.QRadioButton(self.ca_pitch_gbox)
        self.ca_ratio_radio.setObjectName("ca_ratio_radio")
        self.gridLayout.addWidget(self.ca_ratio_radio, 0, 0, 1, 1)
        self.ca_angle_radio = QtWidgets.QRadioButton(self.ca_pitch_gbox)
        self.ca_angle_radio.setObjectName("ca_angle_radio")
        self.gridLayout.addWidget(self.ca_angle_radio, 0, 1, 1, 1)
        self.ca_pitch_label = QtWidgets.QLabel(self.ca_pitch_gbox)
        self.ca_pitch_label.setObjectName("ca_pitch_label")
        self.gridLayout.addWidget(self.ca_pitch_label, 1, 1, 1, 1)
        self.ca_pitch_editbox = QtWidgets.QLineEdit(self.ca_pitch_gbox)
        self.ca_pitch_editbox.setObjectName("ca_pitch_editbox")
        self.gridLayout.addWidget(self.ca_pitch_editbox, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.ca_pitch_gbox)
        self.ca_overhang_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_overhang_label.setMaximumSize(QtCore.QSize(75, 16777215))
        self.ca_overhang_label.setObjectName("ca_overhang_label")
        self.verticalLayout_5.addWidget(self.ca_overhang_label)
        self.ca_overhang_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_overhang_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_overhang_editbox.setObjectName("ca_overhang_editbox")
        self.verticalLayout_5.addWidget(self.ca_overhang_editbox)
        self.ca_roof_gbox = QtWidgets.QGroupBox(self.cathedral_tab)
        self.ca_roof_gbox.setMinimumSize(QtCore.QSize(0, 75))
        self.ca_roof_gbox.setMaximumSize(QtCore.QSize(150, 75))
        self.ca_roof_gbox.setObjectName("ca_roof_gbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ca_roof_gbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ca_eco_radio = QtWidgets.QRadioButton(self.ca_roof_gbox)
        self.ca_eco_radio.setObjectName("ca_eco_radio")
        self.verticalLayout_8.addWidget(self.ca_eco_radio)
        self.ca_al_radio = QtWidgets.QRadioButton(self.ca_roof_gbox)
        self.ca_al_radio.setObjectName("ca_al_radio")
        self.verticalLayout_8.addWidget(self.ca_al_radio)
        self.verticalLayout_5.addWidget(self.ca_roof_gbox)
        self.ca_thick_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_thick_label.setMaximumSize(QtCore.QSize(125, 16777215))
        self.ca_thick_label.setObjectName("ca_thick_label")
        self.verticalLayout_5.addWidget(self.ca_thick_label)
        self.ca_thick_combo = QtWidgets.QComboBox(self.cathedral_tab)
        self.ca_thick_combo.setMaximumSize(QtCore.QSize(125, 16777215))
        self.ca_thick_combo.setObjectName("ca_thick_combo")
        self.verticalLayout_5.addWidget(self.ca_thick_combo)
        self.ca_panel_gbox = QtWidgets.QGroupBox(self.cathedral_tab)
        self.ca_panel_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.ca_panel_gbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ca_panel_gbox.setObjectName("ca_panel_gbox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.ca_panel_gbox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ca_3ply_radio = QtWidgets.QRadioButton(self.ca_panel_gbox)
        self.ca_3ply_radio.setCheckable(True)
        self.ca_3ply_radio.setChecked(False)
        self.ca_3ply_radio.setObjectName("ca_3ply_radio")
        self.verticalLayout_16.addWidget(self.ca_3ply_radio)
        self.ca_4ply_radio = QtWidgets.QRadioButton(self.ca_panel_gbox)
        self.ca_4ply_radio.setObjectName("ca_4ply_radio")
        self.verticalLayout_16.addWidget(self.ca_4ply_radio)
        self.verticalLayout_5.addWidget(self.ca_panel_gbox)
        self.ca_width_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_width_label.setObjectName("ca_width_label")
        self.verticalLayout_5.addWidget(self.ca_width_label)
        self.ca_width_combo = QtWidgets.QComboBox(self.cathedral_tab)
        self.ca_width_combo.setMaximumSize(QtCore.QSize(125, 16777215))
        self.ca_width_combo.setObjectName("ca_width_combo")
        self.verticalLayout_5.addWidget(self.ca_width_combo)
        self.ca_endcut_gbox = QtWidgets.QGroupBox(self.cathedral_tab)
        self.ca_endcut_gbox.setMinimumSize(QtCore.QSize(0, 0))
        self.ca_endcut_gbox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.ca_endcut_gbox.setObjectName("ca_endcut_gbox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.ca_endcut_gbox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.ca_endcut1_radio = QtWidgets.QRadioButton(self.ca_endcut_gbox)
        self.ca_endcut1_radio.setCheckable(True)
        self.ca_endcut1_radio.setChecked(False)
        self.ca_endcut1_radio.setObjectName("ca_endcut1_radio")
        self.verticalLayout_6.addWidget(self.ca_endcut1_radio)
        self.ca_endcut2_radio = QtWidgets.QRadioButton(self.ca_endcut_gbox)
        self.ca_endcut2_radio.setObjectName("ca_endcut2_radio")
        self.verticalLayout_6.addWidget(self.ca_endcut2_radio)
        self.ca_endcut3_radio = QtWidgets.QRadioButton(self.ca_endcut_gbox)
        self.ca_endcut3_radio.setObjectName("ca_endcut3_radio")
        self.verticalLayout_6.addWidget(self.ca_endcut3_radio)
        self.verticalLayout_5.addWidget(self.ca_endcut_gbox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_14.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem8)
        self.ca_peakpanel_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_peakpanel_label.setObjectName("ca_peakpanel_label")
        self.verticalLayout_14.addWidget(self.ca_peakpanel_label)
        self.ca_peakpanel_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_peakpanel_editbox.setMinimumSize(QtCore.QSize(75, 0))
        self.ca_peakpanel_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_peakpanel_editbox.setObjectName("ca_peakpanel_editbox")
        self.verticalLayout_14.addWidget(self.ca_peakpanel_editbox)
        self.ca_awallheight_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_awallheight_label.setObjectName("ca_awallheight_label")
        self.verticalLayout_14.addWidget(self.ca_awallheight_label)
        self.ca_awallheight_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_awallheight_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_awallheight_editbox.setObjectName("ca_awallheight_editbox")
        self.verticalLayout_14.addWidget(self.ca_awallheight_editbox)
        self.ca_cwallheight_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_cwallheight_label.setObjectName("ca_cwallheight_label")
        self.verticalLayout_14.addWidget(self.ca_cwallheight_label)
        self.ca_cwallheight_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_cwallheight_editbox.setObjectName("ca_cwallheight_editbox")
        self.verticalLayout_14.addWidget(self.ca_cwallheight_editbox)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_14)
        self.ca_fig1_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_fig1_label.setMinimumSize(QtCore.QSize(375, 250))
        self.ca_fig1_label.setMaximumSize(QtCore.QSize(375, 250))
        self.ca_fig1_label.setObjectName("ca_fig1_label")
        self.horizontalLayout_3.addWidget(self.ca_fig1_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem10)
        self.ca_awall_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_awall_label.setObjectName("ca_awall_label")
        self.verticalLayout_15.addWidget(self.ca_awall_label)
        self.ca_awall_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_awall_editbox.setMinimumSize(QtCore.QSize(75, 0))
        self.ca_awall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_awall_editbox.setInputMask("")
        self.ca_awall_editbox.setText("")
        self.ca_awall_editbox.setMaxLength(32767)
        self.ca_awall_editbox.setClearButtonEnabled(False)
        self.ca_awall_editbox.setObjectName("ca_awall_editbox")
        self.verticalLayout_15.addWidget(self.ca_awall_editbox)
        self.ca_bwall_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_bwall_label.setObjectName("ca_bwall_label")
        self.verticalLayout_15.addWidget(self.ca_bwall_label)
        self.ca_bwall_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_bwall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_bwall_editbox.setObjectName("ca_bwall_editbox")
        self.verticalLayout_15.addWidget(self.ca_bwall_editbox)
        self.ca_cwall_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_cwall_label.setObjectName("ca_cwall_label")
        self.verticalLayout_15.addWidget(self.ca_cwall_label)
        self.ca_cwall_editbox = QtWidgets.QLineEdit(self.cathedral_tab)
        self.ca_cwall_editbox.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_cwall_editbox.setObjectName("ca_cwall_editbox")
        self.verticalLayout_15.addWidget(self.ca_cwall_editbox)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.ca_floor_label = QtWidgets.QLabel(self.cathedral_tab)
        self.ca_floor_label.setMinimumSize(QtCore.QSize(375, 250))
        self.ca_floor_label.setMaximumSize(QtCore.QSize(375, 250))
        self.ca_floor_label.setObjectName("ca_floor_label")
        self.horizontalLayout_4.addWidget(self.ca_floor_label)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.frame_6 = QtWidgets.QFrame(self.cathedral_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(175, 125))
        self.frame_6.setMaximumSize(QtCore.QSize(175, 300))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.ca_soffit_box = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_soffit_box.sizePolicy().hasHeightForWidth())
        self.ca_soffit_box.setSizePolicy(sizePolicy)
        self.ca_soffit_box.setMinimumSize(QtCore.QSize(0, 0))
        self.ca_soffit_box.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_soffit_box.setReadOnly(True)
        self.ca_soffit_box.setObjectName("ca_soffit_box")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ca_soffit_box)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.ca_drip_box = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_drip_box.sizePolicy().hasHeightForWidth())
        self.ca_drip_box.setSizePolicy(sizePolicy)
        self.ca_drip_box.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_drip_box.setReadOnly(True)
        self.ca_drip_box.setObjectName("ca_drip_box")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ca_drip_box)
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.ca_roof_box = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_roof_box.sizePolicy().hasHeightForWidth())
        self.ca_roof_box.setSizePolicy(sizePolicy)
        self.ca_roof_box.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_roof_box.setReadOnly(True)
        self.ca_roof_box.setObjectName("ca_roof_box")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ca_roof_box)
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.ca_peak_box = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ca_peak_box.sizePolicy().hasHeightForWidth())
        self.ca_peak_box.setSizePolicy(sizePolicy)
        self.ca_peak_box.setMaximumSize(QtCore.QSize(75, 25))
        self.ca_peak_box.setReadOnly(True)
        self.ca_peak_box.setObjectName("ca_peak_box")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ca_peak_box)
        self.verticalLayout_4.addWidget(self.frame_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_22.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.cathedral_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_calc = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_calc.sizePolicy().hasHeightForWidth())
        self.btn_calc.setSizePolicy(sizePolicy)
        self.btn_calc.setToolTip("")
        self.btn_calc.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_calc.setObjectName("btn_calc")
        self.gridLayout_4.addWidget(self.btn_calc, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_7)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_As = QtWidgets.QAction(MainWindow)
        self.action_Save_As.setObjectName("action_Save_As")
        self.action_Print = QtWidgets.QAction(MainWindow)
        self.action_Print.setObjectName("action_Print")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_New)
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.action_Save_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Print)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.label_20.setBuddy(self.ca_soffit_box)
        self.label_21.setBuddy(self.ca_drip_box)
        self.label_22.setBuddy(self.ca_roof_box)
        self.label_23.setBuddy(self.ca_peak_box)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "LivingSpace Toolkit", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Sunrooms/images/Livingspace_Sunrooms_logo.png\"/></p></body></html>", None, -1))
        self.st_scenario_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Scenarios", None, -1))
        self.st_scenario1_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and Pitch", None, -1))
        self.st_scenario2_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and\n"
"Peak Height", None, -1))
        self.st_scenario3_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Max Height and Pitch", None, -1))
        self.st_scenario4_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Soffit Height and Peak Height", None, -1))
        self.st_scenario5_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and\n"
"Max Height with Panels", None, -1))
        self.st_pitch_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pitch", None, -1))
        self.st_pitch_label.setText(QtWidgets.QApplication.translate("MainWindow", "/12 in.", None, -1))
        self.st_angle_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.st_ratio_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Ratio", None, -1))
        self.st_pitch_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0 in. or 0deg.", None, -1))
        self.st_overhang_label.setText(QtWidgets.QApplication.translate("MainWindow", "Overhang", None, -1))
        self.st_overhang_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_roof_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Roofing Type", None, -1))
        self.st_eco_radio.setText(QtWidgets.QApplication.translate("MainWindow", "EcoGreen", None, -1))
        self.st_al_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Aluminum", None, -1))
        self.st_thickness_label.setText(QtWidgets.QApplication.translate("MainWindow", "Thickness", None, -1))
        self.st_panel_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Panel Type", None, -1))
        self.st_3ply_radio.setText(QtWidgets.QApplication.translate("MainWindow", "3-PLY", None, -1))
        self.st_4ply_radio.setText(QtWidgets.QApplication.translate("MainWindow", "4-PLY", None, -1))
        self.st_width_label.setText(QtWidgets.QApplication.translate("MainWindow", "Panel Width", None, -1))
        self.st_endcut_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "End Cuts", None, -1))
        self.st_endcut1_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Uncut Top & Bottom", None, -1))
        self.st_endcut2_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Plumb Cut Top & Bottom", None, -1))
        self.st_endcut3_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Plum Cut Top Only", None, -1))
        self.st_peakpanel_label.setText(QtWidgets.QApplication.translate("MainWindow", "Peak Height\n"
"With Panels", None, -1))
        self.st_peakpanel_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_wall_label.setText(QtWidgets.QApplication.translate("MainWindow", "B Wall Height", None, -1))
        self.st_bwallheight_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_fig1_label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Sunrooms/images/LivingSpace_Studio2.png\"/></p></body></html>", None, -1))
        self.st_awall_label.setText(QtWidgets.QApplication.translate("MainWindow", "A Wall", None, -1))
        self.st_awall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_bwall_label.setText(QtWidgets.QApplication.translate("MainWindow", "B Wall", None, -1))
        self.st_bwall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_cwall_label.setText(QtWidgets.QApplication.translate("MainWindow", "C Wall", None, -1))
        self.st_cwall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.st_floor_label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Sunrooms/images/LivingSpace_FloorPlan2.png\"/></p></body></html>", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Soffit Height", None, -1))
        self.st_soffit_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Drip Edge", None, -1))
        self.st_drip_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Roof at Wall", None, -1))
        self.st_roof_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Peak Height \n"
"Without Panels", None, -1))
        self.st_peak_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.studio_tab), QtWidgets.QApplication.translate("MainWindow", "Studio", None, -1))
        self.ca_scenario_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Scenarios", None, -1))
        self.ca_scenario1_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and Pitch", None, -1))
        self.ca_scenario2_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and\n"
"Peak Height", None, -1))
        self.ca_scenario3_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Max Height and Pitch", None, -1))
        self.ca_scenario4_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Soffit Height and Peak Height", None, -1))
        self.ca_scenario5_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Wall Height and\n"
"Max Height with Panels", None, -1))
        self.ca_pitch_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Pitch", None, -1))
        self.ca_ratio_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Ratio", None, -1))
        self.ca_angle_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.ca_pitch_label.setText(QtWidgets.QApplication.translate("MainWindow", "/12 in.", None, -1))
        self.ca_pitch_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0 in. or 0deg.", None, -1))
        self.ca_overhang_label.setText(QtWidgets.QApplication.translate("MainWindow", "Overhang", None, -1))
        self.ca_overhang_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_roof_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Roofing Type", None, -1))
        self.ca_eco_radio.setText(QtWidgets.QApplication.translate("MainWindow", "EcoGreen", None, -1))
        self.ca_al_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Aluminum", None, -1))
        self.ca_thick_label.setText(QtWidgets.QApplication.translate("MainWindow", "Thickness", None, -1))
        self.ca_panel_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Panel Type", None, -1))
        self.ca_3ply_radio.setText(QtWidgets.QApplication.translate("MainWindow", "3-PLY", None, -1))
        self.ca_4ply_radio.setText(QtWidgets.QApplication.translate("MainWindow", "4-PLY", None, -1))
        self.ca_width_label.setText(QtWidgets.QApplication.translate("MainWindow", "Panel Width", None, -1))
        self.ca_endcut_gbox.setTitle(QtWidgets.QApplication.translate("MainWindow", "End Cuts", None, -1))
        self.ca_endcut1_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Uncut Top & Bottom", None, -1))
        self.ca_endcut2_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Plumb Cut Top & Bottom", None, -1))
        self.ca_endcut3_radio.setText(QtWidgets.QApplication.translate("MainWindow", "Plum Cut Top Only", None, -1))
        self.ca_peakpanel_label.setText(QtWidgets.QApplication.translate("MainWindow", "Peak Height\n"
"With Panels", None, -1))
        self.ca_peakpanel_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_awallheight_label.setText(QtWidgets.QApplication.translate("MainWindow", "A Wall Height", None, -1))
        self.ca_awallheight_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_cwallheight_label.setText(QtWidgets.QApplication.translate("MainWindow", "C Wall Height", None, -1))
        self.ca_cwallheight_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_fig1_label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Sunrooms/images/LivingSpace_Cathedral2.png\"/></p></body></html>", None, -1))
        self.ca_awall_label.setText(QtWidgets.QApplication.translate("MainWindow", "A Wall", None, -1))
        self.ca_awall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_bwall_label.setText(QtWidgets.QApplication.translate("MainWindow", "B Wall", None, -1))
        self.ca_bwall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_cwall_label.setText(QtWidgets.QApplication.translate("MainWindow", "C Wall", None, -1))
        self.ca_cwall_editbox.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\' or 0\"", None, -1))
        self.ca_floor_label.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Sunrooms/images/LivingSpace_FloorPlan2.png\"/></p></body></html>", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "Soffit Height", None, -1))
        self.ca_soffit_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Drip Edge", None, -1))
        self.ca_drip_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Roof at Wall", None, -1))
        self.ca_roof_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Peak Height\n"
"Without Panels", None, -1))
        self.ca_peak_box.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "0\"", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cathedral_tab), QtWidgets.QApplication.translate("MainWindow", "Cathedral", None, -1))
        self.btn_calc.setText(QtWidgets.QApplication.translate("MainWindow", "Calculate", None, -1))
        self.menu_File.setTitle(QtWidgets.QApplication.translate("MainWindow", "&File", None, -1))
        self.action_New.setText(QtWidgets.QApplication.translate("MainWindow", "&New", None, -1))
        self.action_Open.setText(QtWidgets.QApplication.translate("MainWindow", "&Open", None, -1))
        self.action_Save.setText(QtWidgets.QApplication.translate("MainWindow", "&Save", None, -1))
        self.action_Save_As.setText(QtWidgets.QApplication.translate("MainWindow", "&Save As...", None, -1))
        self.action_Print.setText(QtWidgets.QApplication.translate("MainWindow", "&Print", None, -1))
        self.action_Exit.setText(QtWidgets.QApplication.translate("MainWindow", "&Exit", None, -1))

import UI_rc
